routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\Auth\LoginController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Définition des routes pour les articles
Route::resource('post', PostController::class)->except(['show', 'edit', 'update']);

// Route pour l'affichage du formulaire de connexion
Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');

// Route pour la page d'accueil après la connexion
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Route pour la déconnexion (accepte à la fois les requêtes GET et POST)
Route::match(['get', 'post'], '/logout', [App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('logout');

// Route pour la soumission du formulaire de connexion
Route::post('/login', [LoginController::class, 'login']);

Route::get('post/tag/{tag}', [PostController::class, 'indexTag']);

app/Models/Post.php
<?php

namespace App\Models;
use App\Models\Tag;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['titre', 'contenu', 'user_id'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
    public function tags()
{
         return $this->belongsToMany(Tag::class);
}

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function isAdmin()
    {
        return $this->admin; // Assuming 'admin' column in your database
    }
}

app/Models/tag.php
<?php

namespace App\Models;
use App\Models\Post;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class tag extends Model
{
    protected $fillable = ['tag', 'tag_url'];

    public function posts()
    {
        return $this->belongsToMany(Post::class);
    }
    
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\PostRepository;
use App\Http\Requests\PostRequest;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Support\Facades\Auth;

class PostController extends Controller
{
    protected $postRepository;
    protected $nbrPerPage = 4;

    public function __construct(PostRepository $postRepository)
    {
        $this->middleware('auth')->except('index');
        $this->middleware('admin')->only('destroy');
        $this->postRepository = $postRepository;
    }

    public function index()
    {
        $posts = $this->postRepository->getPaginate($this->nbrPerPage);
        $links = $posts->render();

        return view('posts.liste', compact('posts', 'links'));
    }

    public function create()
    {
        return view('posts.add');
    }

    public function store(PostRequest $request)
    {
        $inputs = array_merge($request->all(), ['user_id' => Auth::id()]);
        $this->postRepository->store($inputs);

        return redirect()->route('post.index');
    }

    public function edit($id)
    {
        $post = $this->postRepository->find($id);
    
        return view('posts.edit', compact('post'));
    }

    public function destroy($id)
    {
        $this->postRepository->destroy($id);

        return redirect()->back();
    }
    public function indexTag($tag)
{
    $postRepository = app(PostRepository::class);
    $posts = $postRepository->getWithUserAndTagsForTagPaginate($tag, $this->nbrPerPage);
    $links = $posts->render();

    return view('posts.liste', compact('posts', 'links'))
        ->with('info', 'Résultats pour la recherche du mot-clé : ' . $tag);
}
}

resources/views/home.blade.php
{{-- @extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <p class="alert alert-info">{{ __('You are logged in!') }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection --}}
<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <p class="alert alert-info">{{ __('You are logged in!') }}</p>
                    <!-- Bouton de déconnexion -->
                    <form action="{{ route('logout') }}" method="POST">
                        @csrf
                        <button type="submit" class="btn btn-danger">{{ __('Logout') }}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/posts/add.blade.php
{{-- <!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajout d'un article</title>
    <!-- Inclure les fichiers CSS de Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
    <style>
        .has-error input,
        .has-error textarea {
            border-color: #a94442;
        }

        .has-error small {
            color: #a94442;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-sm-offset-3 col-sm-6">
                <div class="panel panel-info">
                    <div class="panel-heading">Ajout d'un article</div>
                    <div class="panel-body">
                        <form action="{{ route('post.store') }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <input type="text" name="titre" class="form-control" placeholder="Titre">
                                @error('titre')
                                    <small class="text-danger">{{ $message }}</small>
                                @enderror
                            </div>
                            <div class="form-group">
                                <textarea name="contenu" class="form-control" placeholder="Contenu"></textarea>
                                @error('contenu')
                                    <small class="text-danger">{{ $message }}</small>
                                @enderror
                            </div>
                            <button type="submit" class="btn btn-info pull-right">Envoyer !</button>
                        </form>
                    </div>
                </div>
                <a href="javascript:history.back()" class="btn btn-primary">
                    <span class="glyphicon glyphicon-circle-arrow-left"></span> Retour
                </a>
            </div>
        </div>
    </div>
    <!-- Inclure les fichiers JavaScript de Bootstrap (si nécessaire) -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</body>
</html> --}}
@extends('template')

@section('contenu')
<br>
<div class="col-sm-offset-3 col-sm-6">
    <div class="panel panel-info">
        <div class="panel-heading">Ajout d'un article</div>
        <div class="panel-body">
            <form method="POST" action="{{ route('post.store') }}">
                @csrf
                <div class="form-group {{ $errors->has('titre') ? 'has-error' : '' }}">
                    <input type="text" name="titre" class="form-control" placeholder="Titre">
                    @error('titre')
                    <small class="text-danger">{{ $message }}</small>
                    @enderror
                </div>
                <div class="form-group {{ $errors->has('contenu') ? 'has-error' : '' }}">
                    <textarea name="contenu" class="form-control" placeholder="Contenu"></textarea>
                    @error('contenu')
                    <small class="text-danger">{{ $message }}</small>
                    @enderror
                </div>
                <div class="form-group {{ $errors->has('tags') ? 'has-error' : '' }}">
                    <input type="text" name="tags" class="form-control" placeholder="Entrez les mots-clés séparés par des virgules">
                    @error('tags')
                    <small class="text-danger">{{ $message }}</small>
                    @enderror
                </div>
                <button type="submit" class="btn btn-info pull-right">Envoyer !</button>
            </form>
        </div>
    </div>
    <a href="javascript:history.back()" class="btn btn-primary">
        <span class="glyphicon glyphicon-circle-arrow-left"></span> Retour
    </a>
</div>
@endsection

resources/views/posts/liste.blade.php
{{-- @extends('template')
@section('header')
<div class="container">
  <div class="row">
      <div class="col-md-12">
          <div class="header">
              @if(Auth::check())
                  <div class="btn-group pull-right">
                      <a href="{{ route('post.create') }}" class="btn btn-info">Créer un article</a>
                      <form action="{{ route('logout') }}" method="POST">
                          @csrf
                          <button type="submit" class="btn btn-warning">Déconnexion</button>
                      </form>
                  </div>
              @else
                  <a href="{{ route('login') }}" class="btn btn-info pull-right">Se connecter</a>
              @endif
          </div>
      </div>
  </div>
  @if(isset($info))
      <div class="row alert alert-info">{{$info}}</div>
  @endif
  {!!$links!!}
  @foreach($posts as $post)
      <article class="row bg-primary">
          <div class="col-md-12">
              <header>
                  <h1>{{$post->titre}}</h1>
              </header>
              <hr>
              <section>
                  <p>{{$post->contenu}}</p>
                  @if(Auth::check() && Auth::user()->admin)
                      <form action="{{ route('post.destroy', $post->id) }}" method="POST">
                          @csrf
                          @method('DELETE')
                          <button type="submit" class="btn btn-danger">Supprimer cet article</button>
                      </form>
                  @endif
                  <em class="pull-right">
                      <span class="glyphicon glyphicon-pencil"></span> 
                      {{$post->user->name}} le {{ $post->created_at->format('d-m-Y') }}
                  </em>
              </section>
          </div>
      </article>
  @endforeach
  {!!$links!!}
</div>
<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"> --}}



















{{-- @extends('template')

@section('header')
@if(Auth::check())
<div class="btn-group pull-right">
    <a href="{{ route('post.create') }}" class="btn btn-info">Créer un article</a>
    <a href="{{ route('logout') }}" class="btn btn-warning">Déconnexion</a>
</div>
@else
    <a href="{{ route('login') }}" class="btn btn-info pull-right">Se connecter</a>
@endif
@endsection

@section('contenu')
@if(isset($info))
<div class="row alert alert-info">{{$info}}</div>
@endif
{!! $links !!}
@foreach($posts as $post)
<article class="row bg-primary">
    <div class="col-md-12">
        <header>
            <h1>{{$post->titre}}</h1>
        </header>
        <hr>
        <section>
            <p>{{$post->contenu}}</p>
            @if(Auth::check() && Auth::user()->admin)
            <form method="POST" action="{{ route('post.destroy', $post->id) }}">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-danger">Supprimer cet article</button>
            </form>
            @endif
            <em class="pull-right">
                <span class="glyphicon glyphicon-pencil"></span>
                {{$post->user->name}} le {{ $post->created_at->format('d-m-Y') }}
            </em>
        </section>
    </div>
</article>
@endforeach
@endsection --}}




@extends('template')

@section('header')
@if(Auth::check())
<div class="btn-group pull-right">
    <a href="{{ route('post.create') }}" class="btn btn-info">Créer un article</a>
    <a href="{{ url('logout') }}" class="btn btn-warning">Déconnexion</a>
</div>
@else
<a href="{{ url('login') }}" class="btn btn-info pull-right">Se connecter</a>
@endif
@endsection

@section('contenu')
@if(isset($info))
<div class="row alert alert-info">{{ $info }}</div>
@endif

{{ $links }}

@foreach($posts as $post)
<article class="row bg-primary">
    <div class="col-md-12">
        <header>
            <h1>{{ $post->titre }}
                <div class="pull-right">
                    @foreach($post->tags as $tag)
                    <a href="{{ url('post/tag/' . $tag->tag_url) }}" class="btn btn-xs btn-info">{{ $tag->tag }}</a>
                    @endforeach
                </div>
            </h1>
        </header>
        <hr>
        <section>
            <p>{{ $post->contenu }}</p>
            @if(Auth::check() && Auth::user()->admin)
            {!! Form::open(['method'=>'DELETE', 'route'=>['post.destroy', $post->id]]) !!}
            {!! Form::submit('Supprimer cet article', ['class'=>'btn article']) !!}
            {!! Form::close() !!}
            @endif
            <em class="pull-right">
                <span class="glyphicon glyphicon-pencil"></span>{{ $post->user->name }} le {{ $post->created_at->format('d-m-Y') }}
            </em>
        </section>
    </div>
</article>
<br>
@endforeach

{{ $links }}
@endsection

resources/views/template.blade.php
{{-- <!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mon joli site</title>
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
        textarea {
            resize: none;
        }
    </style>
</head>
<body>
    <header class="jumbotron">
        <div class="container">
            <h1 class="page-header"><a href="{{ route('post.index') }}">Mon joli blog</a></h1>
            @yield('header')
        </div>
    </header>
    <div class="container">
        @yield('contenu')
    </div>
</body>
</html> --}}



<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mon joli site</title>
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>textarea {resize:none;}</style>
</head>
<body>
<header class="jumbotron">
    <div class="container">
        <h1 class="page-header"><a href="{{ route('post.index') }}">Mon joli blog</a></h1>
        @yield('header')
    </div>
</header>
<div class="container">
    @yield('contenu')
</div>
</body>
</html>